name: Push master to gh-pages
on: workflow_dispatch
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Fetch master
        run: git fetch origin master
      - name: Merge master -> gh-pages
        run: git merge --ff-only origin/master
      - name: Push
        run: git push origin gh-pages
